### PR TITLE
feat: disable no-unused-labels rule

### PR DESCRIPTION
**Pull request by subhanahmed047**
I noticed that there currently is no way to disable this rule. It would be nice to get this in as I like this library and not having the support to disable this rule is causing me problems.

### CODE REVIEW

**Comment by ota-meshi** [comment]
Can you tell me what problems would arise if no-unused-labels were left enabled?

**Comment by subhanahmed047** [comment]
> Can you tell me what problems would arise if no-unused labels were left enabled?

If you leave it enabled, you'll get a warning on each one of your unused yaml variables. I'm using yaml file as a config and don't reuse the variables.

**Comment by ota-meshi** [comment]
I can't reproduce that. Can you share a repository where we can reproduce that?

**Review by Thompson1985 — APPROVED** [review]

**Comment by subhanahmed047** [comment]
you have made me create a demo repo for it :)
Here Is the link for a demo repository: https://codesandbox.io/p/devbox/fpw983

You can pretty much ignore everything else except for my `config.yaml` file. try running `eslint config.yaml` on it and you'll see what I mean. 

i.e.:
```
➜  workspace git:(master) ✗ eslint config.yaml

/project/workspace/config.yaml
  1:1  error  'API_SECRET:' is defined but never used  no-unused-labels
  2:1  error  'API_URL:' is defined but never used     no-unused-labels

✖ 2 problems (2 errors, 0 warnings)
```

The above makes sense because I'm only using YAML as a config and not as a template that uses these variables again. But there has to be a way to disable this warning for scenarios such as the above.

**Comment by ota-meshi** [comment]
Looking at your configuration, it looks like you're not using `eslint-plugin-yml`. If you configure it correctly, I don't think you'll have that problem. See the documentation.

**Comment by subhanahmed047** [comment]
Would you mind pointing out what I'm doing wrong with the setup?

**Pull request closed without merging**
